local mod = get_mod("Preysight")

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{
				setting_id = "preysight_general_group",
				type = "group",
				sub_widgets = {
					{
						setting_id = "preysight_keybind_toggle",
						type = "keybind",
						default_value = {},
						keybind_global = false,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "_kb_toggle",
						title = "preysight_keybind_toggle",
						tooltip = "preysight_keybind_toggle_tooltip",
					},
					{
						setting_id = "preysight_always_on",
						type = "checkbox",
						default_value = false,
						title = "preysight_always_on",
						tooltip = "preysight_always_on_tooltip",
					},
				},
			},
			{
				setting_id = "preysight_headgear_group",
				type = "group",
				sub_widgets = {
					{
						setting_id = "preysight_hue_source",
						type = "dropdown",
						default_value = "lens",
						title = "preysight_hue_source",
						tooltip = "preysight_hue_source_tooltip",
						options = {
							{ text = "preysight_hue_source_lens", value = "lens" },
							{ text = "preysight_hue_source_fixed", value = "fixed", show_widgets = { 1 } },
						},
						sub_widgets = {
							{
								setting_id = "preysight_fixed_colour",
								type = "color",
								default_value = { 255, 64, 255, 26 },
								has_alpha = false,
								title = "preysight_fixed_colour",
							},
						},
					},
					{
						setting_id = "preysight_teach_head",
						type = "checkbox",
						default_value = false,
						title = "preysight_teach_head",
						tooltip = "preysight_teach_head_tooltip",
					},
					{
						setting_id = "preysight_forget_taught",
						type = "button",
						button_text = "preysight_forget_taught",
						button_trigger = "pressed",
						function_name = "_forget_taught",
						title = "preysight_forget_taught",
						tooltip = "preysight_forget_taught_tooltip",
					},
				},
			},
			{
				setting_id = "preysight_tuning_group",
				type = "group",
				sub_widgets = {
					{
						setting_id = "preysight_exposure",
						type = "numeric",
						default_value = 3.0,
						range = { 0, 3.5 },
						decimals_number = 1,
						step_size_value = 0.1,
						title = "preysight_exposure",
						tooltip = "preysight_exposure_tooltip",
					},
					{
						setting_id = "preysight_greyscale",
						type = "numeric",
						default_value = 1.0,
						range = { 0, 1 },
						decimals_number = 2,
						step_size_value = 0.05,
						title = "preysight_greyscale",
						tooltip = "preysight_greyscale_tooltip",
					},
					{
						setting_id = "preysight_blur",
						type = "numeric",
						default_value = 0.1,
						range = { 0, 0.3 },
						decimals_number = 2,
						step_size_value = 0.01,
						title = "preysight_blur",
						tooltip = "preysight_blur_tooltip",
					},
					{
						setting_id = "preysight_blend_in",
						type = "numeric",
						default_value = 1.0,
						range = { 0, 3 },
						decimals_number = 1,
						step_size_value = 0.1,
						title = "preysight_blend_in",
						tooltip = "preysight_blend_in_tooltip",
					},
					{
						setting_id = "preysight_blend_out",
						type = "numeric",
						default_value = 0.6,
						range = { 0, 3 },
						decimals_number = 1,
						step_size_value = 0.1,
						title = "preysight_blend_out",
						tooltip = "preysight_blend_out_tooltip",
					},
				},
			},
			{
				setting_id = "preysight_overlay_group",
				type = "group",
				sub_widgets = {
					{
						setting_id = "preysight_wash_alpha",
						type = "numeric",
						default_value = 0.25,
						range = { 0, 1 },
						decimals_number = 2,
						step_size_value = 0.01,
						title = "preysight_wash_alpha",
						tooltip = "preysight_wash_alpha_tooltip",
					},
					{
						setting_id = "preysight_scanline_alpha",
						type = "numeric",
						default_value = 0.15,
						range = { 0, 1 },
						decimals_number = 2,
						step_size_value = 0.01,
						title = "preysight_scanline_alpha",
						tooltip = "preysight_scanline_alpha_tooltip",
					},
					{
						setting_id = "preysight_grain_alpha",
						type = "numeric",
						default_value = 0.25,
						range = { 0, 1 },
						decimals_number = 2,
						step_size_value = 0.01,
						title = "preysight_grain_alpha",
						tooltip = "preysight_grain_alpha_tooltip",
					},
					{
						setting_id = "preysight_vignette_alpha",
						type = "numeric",
						default_value = 0.8,
						range = { 0, 1 },
						decimals_number = 2,
						step_size_value = 0.01,
						title = "preysight_vignette_alpha",
						tooltip = "preysight_vignette_alpha_tooltip",
					},
				},
			},
			{
				setting_id = "preysight_illuminator_group",
				type = "group",
				sub_widgets = {
					{
						setting_id = "preysight_illuminator",
						type = "checkbox",
						default_value = true,
						title = "preysight_illuminator",
						tooltip = "preysight_illuminator_tooltip",
					},
					{
						setting_id = "preysight_illuminator_intensity",
						type = "numeric",
						default_value = 4,
						range = { 0, 20 },
						decimals_number = 1,
						step_size_value = 0.5,
						title = "preysight_illuminator_intensity",
						tooltip = "preysight_illuminator_intensity_tooltip",
					},
					{
						setting_id = "preysight_illuminator_range",
						type = "numeric",
						default_value = 15,
						range = { 2, 30 },
						decimals_number = 0,
						step_size_value = 1,
						title = "preysight_illuminator_range",
						tooltip = "preysight_illuminator_range_tooltip",
					},
					{
						setting_id = "preysight_illuminator_offset",
						type = "numeric",
						default_value = -1.5,
						range = { -5, 5 },
						decimals_number = 1,
						step_size_value = 0.1,
						title = "preysight_illuminator_offset",
						tooltip = "preysight_illuminator_offset_tooltip",
					},
					{
						setting_id = "preysight_illuminator_height",
						type = "numeric",
						default_value = 1.5,
						range = { -2, 5 },
						decimals_number = 1,
						step_size_value = 0.1,
						title = "preysight_illuminator_height",
						tooltip = "preysight_illuminator_height_tooltip",
					},
				},
			},
		},
	},
}
